// ============================================================
// SLIDE DATA – Chapter 1: Gradient, Divergence, and Curl
// Group: Heroes | Faculty of Science, Alexandria University
// ============================================================

export const TEAM_MEMBERS = [
  { name: "Kareem Osama Ebrahim Ragab",        slides: [1,2,3,4]   },
  { name: "Yousef Mohamed Elsayed Ismail",      slides: [5,6,7,8]   },
  { name: "Khalid Ahmed Sedik Ahmed",           slides: [9,10,11,12] },
  { name: "Yahya Omar Mahmoud Deyab",           slides: [13,14,15,16] },
  { name: "Ahmed Saied ELsayed Kamal",          slides: [17,18,19,20] },
  { name: "Mahmoud Wael Mostafa Mahmoud",       slides: [21,22,23,24] },
  { name: "Amr Hamdy Fathy Abdel Salam",        slides: [25,26,27,28] },
  { name: "Abdelrahman Mahmoud Elsayed Mahmoud",slides: [29,30,31,32] },
  { name: "Belal Elsayed Saad Elsayed",         slides: [33,34,35,36] },
  { name: "Ahmed Khaled Ramadan Mohamed",       slides: [37,38,39,40] },
];

export const slides = [
  // ─────────────────────────────────────────────────────────────
  // TITLE SLIDE (slide 0)
  // ─────────────────────────────────────────────────────────────
  {
    id: 0,
    type: "title",
    chapter: "Chapter 1",
    title: "Gradient, Divergence & Curl",
    subtitle: "in Mechanics",
    college: "Faculty of Science — Alexandria University",
    instructors: ["Dr. Mona Gad", "Dr. Mona Khattab"],
    group: "Heroes",
    narration: "Welcome to Chapter 1: Gradient, Divergence, and Curl in Mechanics. This presentation was prepared by Group Heroes at the Faculty of Science, Alexandria University, under the supervision of Doctor Mona Gad and Doctor Mona Khattab.",
  },

  // ─────────────────────────────────────────────────────────────
  // KAREEM – Slides 1–4
  // ─────────────────────────────────────────────────────────────
  {
    id: 1,
    type: "content",
    presenter: "Kareem Osama Ebrahim Ragab",
    slideNum: 1,
    topic: "Vector Differential Operator ∇",
    tag: "Definition",
    tagColor: "blue",
    formulas: [
      { latex: "\\nabla = \\mathbf{i}\\frac{\\partial}{\\partial x} + \\mathbf{j}\\frac{\\partial}{\\partial y} + \\mathbf{k}\\frac{\\partial}{\\partial z}", glow: "blue" },
    ],
    bullets: [
      "∇ (nabla / del) is called the Vector Differential Operator",
      "It behaves like a vector but contains partial derivative operators",
      "It does NOT have a value by itself — it must act on a scalar or vector field",
      "Forms the foundation of Gradient, Divergence, and Curl",
    ],
    visual: "nabla",
    narration: "We begin with the Vector Differential Operator, denoted by the symbol nabla or del. It is defined as i times partial over partial x, plus j times partial over partial y, plus k times partial over partial z. By itself, nabla is just an operator — it has no numerical value. But when it acts on a scalar or vector field, it produces the gradient, divergence, or curl. This operator is the fundamental building block for all of vector calculus in mechanics.",
  },
  {
    id: 2,
    type: "content",
    presenter: "Kareem Osama Ebrahim Ragab",
    slideNum: 2,
    topic: "The Gradient of a Scalar Field",
    tag: "Gradient",
    tagColor: "blue",
    formulas: [
      { latex: "\\nabla\\phi = \\mathbf{i}\\frac{\\partial\\phi}{\\partial x} + \\mathbf{j}\\frac{\\partial\\phi}{\\partial y} + \\mathbf{k}\\frac{\\partial\\phi}{\\partial z}", glow: "blue" },
    ],
    bullets: [
      "∇ϕ is a VECTOR field derived from scalar field ϕ",
      "Points in the direction of maximum increase of ϕ",
      "Its magnitude = rate of greatest increase",
      "Used in physics: temperature, pressure, potential fields",
    ],
    visual: "gradient3d",
    narration: "The Gradient of a scalar field phi is found by applying nabla to phi. The result is a vector: i times partial phi over partial x, plus j times partial phi over partial y, plus k times partial phi over partial z. This vector always points in the direction of steepest ascent of the scalar field. Think of a mountain: the gradient at any point on the hill points directly uphill in the steepest direction. In physics, if phi is temperature, the gradient points toward increasing temperature.",
  },
  {
    id: 3,
    type: "content",
    presenter: "Kareem Osama Ebrahim Ragab",
    slideNum: 3,
    topic: "Gradient Perpendicular to Surfaces",
    tag: "Key Property",
    tagColor: "purple",
    formulas: [
      { latex: "\\phi(x,y,z) = c \\;\\Rightarrow\\; \\nabla\\phi \\perp \\text{surface}", glow: "purple" },
      { latex: "d\\phi = \\nabla\\phi \\cdot d\\mathbf{r} = 0 \\quad \\text{(on surface \\(\\phi=c\\))}", glow: "blue" },
    ],
    bullets: [
      "On a level surface ϕ = c, the value of ϕ does not change",
      "Therefore dϕ = ∇ϕ · dr = 0 along the surface",
      "This means ∇ϕ is perpendicular (normal) to the surface",
      "Important: ∇ϕ gives the normal vector to any level surface",
    ],
    visual: "normalSurface",
    narration: "A key property of the gradient is that it is always perpendicular to surfaces of constant phi, known as level surfaces or equipotential surfaces. If we move along such a surface, phi does not change, so d-phi equals zero. But d-phi also equals the dot product of gradient phi with d-r. For this dot product to be zero, gradient phi must be perpendicular to d-r, meaning it is perpendicular to the surface itself. This property is used extensively to find normal vectors to surfaces.",
  },
  {
    id: 4,
    type: "content",
    presenter: "Kareem Osama Ebrahim Ragab",
    slideNum: 4,
    topic: "Directional Derivative",
    tag: "Application",
    tagColor: "teal",
    formulas: [
      { latex: "\\frac{d\\phi}{ds} = \\nabla\\phi \\cdot \\hat{a}", glow: "blue" },
      { latex: "\\hat{a} = \\frac{\\mathbf{a}}{|\\mathbf{a}|} \\quad\\text{(unit vector in direction }\\mathbf{a}\\text{)}", glow: "teal" },
    ],
    bullets: [
      "Rate of change of ϕ in direction â",
      "â is a unit vector in the chosen direction",
      "Maximum value = |∇ϕ|, achieved along gradient direction",
      "Minimum (most negative) along direction opposite to gradient",
    ],
    example: {
      title: "Example",
      steps: [
        "Given \\phi = 2xy - z^2 at point (1, 2, -1), direction \\mathbf{a} = 2\\mathbf{i} + \\mathbf{j} - 2\\mathbf{k}",
        "\\nabla\\phi = 2y\\,\\mathbf{i} + 2x\\,\\mathbf{j} - 2z\\,\\mathbf{k}",
        "\\text{At }(1,2,-1): \\;\\nabla\\phi = 4\\mathbf{i} + 2\\mathbf{j} + 2\\mathbf{k}",
        "\\hat{a} = \\tfrac{1}{3}(2\\mathbf{i} + \\mathbf{j} - 2\\mathbf{k})",
        "\\frac{d\\phi}{ds} = \\nabla\\phi \\cdot \\hat{a} = \\tfrac{1}{3}(8+2-4) = 2",
      ],
    },
    visual: "directional",
    narration: "The directional derivative tells us the rate of change of phi in any specified direction. The formula is d-phi over d-s equals the dot product of gradient phi with the unit vector a-hat in that direction. The maximum directional derivative occurs exactly along the gradient direction, and its value equals the magnitude of the gradient. Let us compute an example: given phi equals 2xy minus z squared at the point 1, 2, negative 1, in the direction 2i plus j minus 2k. We first find gradient phi equals 4i plus 2j plus 2k at that point. The unit vector is one-third times 2i plus j minus 2k. The directional derivative is then 4 times 2/3 plus 2 times 1/3 plus 2 times negative 2/3, which equals 2.",
  },

  // ─────────────────────────────────────────────────────────────
  // YOUSEF – Slides 5–8
  // ─────────────────────────────────────────────────────────────
  {
    id: 5,
    type: "content",
    presenter: "Yousef Mohamed Elsayed Ismail",
    slideNum: 5,
    topic: "Divergence of a Vector Field",
    tag: "Definition",
    tagColor: "blue",
    formulas: [
      { latex: "\\nabla \\cdot \\mathbf{V} = \\frac{\\partial V_1}{\\partial x} + \\frac{\\partial V_2}{\\partial y} + \\frac{\\partial V_3}{\\partial z}", glow: "blue" },
    ],
    bullets: [
      "Takes a vector field V and returns a scalar field",
      "Positive divergence → source (fluid spreading out)",
      "Negative divergence → sink (fluid converging in)",
      "Zero divergence → Solenoidal field (no sources/sinks)",
    ],
    example: {
      title: "Solenoidal Example",
      steps: [
        "\\mathbf{V} = x^2\\mathbf{i} + y^2\\mathbf{j} - 2z\\mathbf{k}",
        "\\nabla\\cdot\\mathbf{V} = 2x + 2y - 2",
        "\\text{Field is solenoidal only if }\\nabla\\cdot\\mathbf{V}=0",
      ],
    },
    visual: "divergence",
    narration: "The Divergence of a vector field V is defined as nabla dot V, which equals partial V1 over partial x, plus partial V2 over partial y, plus partial V3 over partial z. Notice it takes a vector field as input and produces a scalar. Physically, divergence measures how much a vector field is spreading outward from a point. If the divergence is positive at a point, that point is a source — like water flowing outward from a tap. If negative, it is a sink — like water draining into a hole. If the divergence is identically zero everywhere, the field is called solenoidal.",
  },
  {
    id: 6,
    type: "content",
    presenter: "Yousef Mohamed Elsayed Ismail",
    slideNum: 6,
    topic: "Curl of a Vector Field",
    tag: "Definition",
    tagColor: "purple",
    formulas: [
      { latex: "\\nabla \\times \\mathbf{V} = \\begin{vmatrix} \\mathbf{i} & \\mathbf{j} & \\mathbf{k} \\\\ \\tfrac{\\partial}{\\partial x} & \\tfrac{\\partial}{\\partial y} & \\tfrac{\\partial}{\\partial z} \\\\ V_1 & V_2 & V_3 \\end{vmatrix}", glow: "purple" },
      { latex: "= \\left(\\frac{\\partial V_3}{\\partial y}-\\frac{\\partial V_2}{\\partial z}\\right)\\mathbf{i} - \\left(\\frac{\\partial V_3}{\\partial x}-\\frac{\\partial V_1}{\\partial z}\\right)\\mathbf{j} + \\left(\\frac{\\partial V_2}{\\partial x}-\\frac{\\partial V_1}{\\partial y}\\right)\\mathbf{k}", glow: "blue" },
    ],
    bullets: [
      "Takes a vector field and returns a vector field",
      "Measures the rotation / circulation of the field",
      "Irrotational field: ∇ × V = 0",
      "Axis of curl vector = axis of rotation; magnitude = angular speed",
    ],
    visual: "curl",
    narration: "The Curl of a vector field V is defined as nabla cross V. It is computed as the determinant of a 3×3 matrix with i, j, k in the first row; partial over partial x, partial over partial y, partial over partial z in the second row; and V1, V2, V3 in the third row. The result is a vector field. Physically, the curl measures the rotational tendency of the field at each point. If you placed a tiny paddle wheel in a fluid flowing with velocity V, the curl tells you how fast and in what direction the paddle wheel would spin. An irrotational field has zero curl everywhere.",
  },
  {
    id: 7,
    type: "content",
    presenter: "Yousef Mohamed Elsayed Ismail",
    slideNum: 7,
    topic: "Key Vector Identities",
    tag: "Identities",
    tagColor: "gold",
    formulas: [
      { latex: "\\nabla \\times (\\nabla\\phi) = \\mathbf{0} \\quad \\text{(curl of gradient = 0)}", glow: "gold" },
      { latex: "\\nabla \\cdot (\\nabla \\times \\mathbf{A}) = 0 \\quad \\text{(div of curl = 0)}", glow: "gold" },
      { latex: "\\nabla^2\\phi = \\frac{\\partial^2\\phi}{\\partial x^2} + \\frac{\\partial^2\\phi}{\\partial y^2} + \\frac{\\partial^2\\phi}{\\partial z^2} \\quad \\text{(Laplacian)}", glow: "blue" },
    ],
    bullets: [
      "curl(grad ϕ) = 0: gradient fields are irrotational",
      "div(curl A) = 0: curl fields are solenoidal",
      "Laplacian ∇² = div(grad) measures second-order variation",
      "These identities are fundamental in physics & engineering",
    ],
    visual: "identities",
    narration: "Three fundamental vector identities underpin much of mathematical physics. First: the curl of any gradient is identically zero. This means if a field is a gradient of some scalar, it has no rotational component. Second: the divergence of any curl is identically zero. This means curl fields have no sources or sinks. Third: the Laplacian of phi, written nabla-squared phi, equals the sum of the three second partial derivatives. It measures how much phi at a point differs from the average of its surroundings. All three appear constantly in mechanics, electromagnetism, and fluid dynamics.",
  },
  {
    id: 8,
    type: "content",
    presenter: "Yousef Mohamed Elsayed Ismail",
    slideNum: 8,
    topic: "Laplacian — Applications",
    tag: "Applications",
    tagColor: "teal",
    formulas: [
      { latex: "\\nabla^2\\phi = 0 \\quad \\text{(Laplace equation — steady-state)}", glow: "teal" },
      { latex: "\\nabla^2\\phi = \\frac{1}{\\alpha}\\frac{\\partial\\phi}{\\partial t} \\quad \\text{(Heat / diffusion equation)}", glow: "blue" },
      { latex: "\\nabla^2\\phi = \\frac{1}{c^2}\\frac{\\partial^2\\phi}{\\partial t^2} \\quad \\text{(Wave equation)}", glow: "purple" },
    ],
    bullets: [
      "Laplace equation: electrostatics, steady heat flow, fluid potential",
      "Heat equation: temperature diffusion through a medium",
      "Wave equation: sound, light, quantum mechanics",
      "∇² appears in every branch of physics and engineering",
    ],
    visual: "laplacian",
    narration: "The Laplacian operator appears in the most important partial differential equations in physics. When nabla-squared phi equals zero, we have Laplace's equation, which describes steady-state heat distribution or electrostatic potentials with no sources. When nabla-squared phi equals the time rate of change divided by thermal diffusivity, we have the heat equation, describing how temperature spreads through a material. When nabla-squared phi equals the second time derivative divided by wave speed squared, we get the wave equation, describing light, sound, and vibrations. Mastering the Laplacian unlocks all these physical phenomena.",
  },

  // ─────────────────────────────────────────────────────────────
  // KHALID – Slides 9–12
  // ─────────────────────────────────────────────────────────────
  {
    id: 9,
    type: "content",
    presenter: "Khalid Ahmed Sedik Ahmed",
    slideNum: 9,
    topic: "Gradient — Worked Example",
    tag: "Example",
    tagColor: "teal",
    formulas: [
      { latex: "\\phi = 2y^2 - 3xz + z^3", glow: "blue" },
    ],
    example: {
      title: "Find ∇ϕ and evaluate at (1, –1, 2)",
      steps: [
        "\\frac{\\partial\\phi}{\\partial x} = -3z \\;\\Rightarrow\\; -3(2) = -6",
        "\\frac{\\partial\\phi}{\\partial y} = 4y \\;\\Rightarrow\\; 4(-1) = -4",
        "\\frac{\\partial\\phi}{\\partial z} = -3x + 3z^2 \\;\\Rightarrow\\; -3(1)+3(4) = 9",
        "\\nabla\\phi = -6\\,\\mathbf{i} - 4\\,\\mathbf{j} + 9\\,\\mathbf{k} \\quad\\text{at }(1,-1,2)",
        "|\\nabla\\phi| = \\sqrt{36+16+81} = \\sqrt{133} \\approx 11.53",
      ],
    },
    bullets: [
      "Compute each partial derivative separately",
      "Substitute the given point coordinates",
      "Assemble the gradient vector components",
      "Magnitude = rate of maximum increase at that point",
    ],
    visual: "gradientCalc",
    narration: "Let us work through a complete gradient example from the textbook. Given phi equals 2y squared minus 3xz plus z cubed, we find gradient phi at the point (1, negative 1, 2). The partial with respect to x is negative 3z, which gives negative 6 at our point. The partial with respect to y is 4y, giving negative 4. The partial with respect to z is negative 3x plus 3z squared, which equals negative 3 plus 12, giving 9. Therefore the gradient at this point is negative 6i minus 4j plus 9k. Its magnitude, the maximum rate of increase, is the square root of 36 plus 16 plus 81, approximately 11.53.",
  },
  {
    id: 10,
    type: "content",
    presenter: "Khalid Ahmed Sedik Ahmed",
    slideNum: 10,
    topic: "Divergence — Worked Example",
    tag: "Example",
    tagColor: "teal",
    formulas: [
      { latex: "\\mathbf{V} = 2x\\,\\mathbf{i} + yz\\,\\mathbf{j} - z^2\\,\\mathbf{k}", glow: "blue" },
    ],
    example: {
      title: "Find ∇ · V",
      steps: [
        "V_1 = 2x \\;\\Rightarrow\\; \\frac{\\partial V_1}{\\partial x} = 2",
        "V_2 = yz \\;\\Rightarrow\\; \\frac{\\partial V_2}{\\partial y} = z",
        "V_3 = -z^2 \\;\\Rightarrow\\; \\frac{\\partial V_3}{\\partial z} = -2z",
        "\\nabla\\cdot\\mathbf{V} = 2 + z - 2z = 2 - z",
        "\\text{At }(1,2,3):\\; \\nabla\\cdot\\mathbf{V} = 2-3 = -1 \\;(\\text{sink})",
      ],
    },
    bullets: [
      "Take partial of each component w.r.t. its own variable",
      "Sum the three partial derivatives",
      "Positive → sources present; Negative → sinks present",
      "Zero → solenoidal (conservation of mass / flux)",
    ],
    visual: "divergence",
    narration: "For our divergence example, take V equals 2x i plus yz j minus z squared k. We compute the divergence as follows: partial of 2x with respect to x gives 2. Partial of yz with respect to y gives z. Partial of negative z squared with respect to z gives negative 2z. So divergence of V equals 2 plus z minus 2z, which simplifies to 2 minus z. At the specific point (1, 2, 3), this gives 2 minus 3 equals negative 1. The negative sign indicates a sink at that point — the field is converging inward.",
  },
  {
    id: 11,
    type: "content",
    presenter: "Khalid Ahmed Sedik Ahmed",
    slideNum: 11,
    topic: "Curl — Worked Example",
    tag: "Example",
    tagColor: "purple",
    formulas: [
      { latex: "\\mathbf{A} = xz\\,\\mathbf{i} + xy\\,\\mathbf{j} + yz\\,\\mathbf{k}", glow: "purple" },
    ],
    example: {
      title: "Find ∇ × A",
      steps: [
        "\\mathbf{i}\\text{-component}: \\frac{\\partial(yz)}{\\partial y} - \\frac{\\partial(xy)}{\\partial z} = z - 0 = z",
        "\\mathbf{j}\\text{-component}: \\frac{\\partial(xz)}{\\partial z} - \\frac{\\partial(yz)}{\\partial x} = x - 0 = x \\;(\\text{subtract, so }-x)",
        "\\mathbf{k}\\text{-component}: \\frac{\\partial(xy)}{\\partial x} - \\frac{\\partial(xz)}{\\partial y} = y - 0 = y",
        "\\nabla\\times\\mathbf{A} = z\\,\\mathbf{i} - x\\,\\mathbf{j} + y\\,\\mathbf{k}",
      ],
    },
    bullets: [
      "Expand the 3×3 determinant by cofactors",
      "Note the sign change on the j-component",
      "Result shows local rotation of the field",
      "At origin (0,0,0): curl A = 0 → irrotational at origin",
    ],
    visual: "curlCalc",
    narration: "Now let us compute the curl of A equals xz i plus xy j plus yz k. We expand the determinant. The i-component is partial of yz over partial y minus partial of xy over partial z, giving z minus 0 equals z. The j-component is partial of xz over partial z minus partial of yz over partial x, giving x minus 0 equals x, but with a negative sign due to the determinant, so we get negative x. The k-component is partial of xy over partial x minus partial of xz over partial y, giving y minus 0 equals y. Therefore curl A equals z i minus x j plus y k. This vector describes the rotational character of the field at each point.",
  },
  {
    id: 12,
    type: "content",
    presenter: "Khalid Ahmed Sedik Ahmed",
    slideNum: 12,
    topic: "Combined Identity: div(curl A) = 0",
    tag: "Proof",
    tagColor: "gold",
    formulas: [
      { latex: "\\nabla \\cdot (\\nabla \\times \\mathbf{A}) = 0 \\quad \\text{always}", glow: "gold" },
    ],
    example: {
      title: "Verify with A = xz i + xy j + yz k",
      steps: [
        "\\nabla\\times\\mathbf{A} = z\\,\\mathbf{i} - x\\,\\mathbf{j} + y\\,\\mathbf{k}\\quad\\text{(from slide 11)}",
        "\\nabla\\cdot(\\nabla\\times\\mathbf{A}) = \\frac{\\partial z}{\\partial x} + \\frac{\\partial(-x)}{\\partial y} + \\frac{\\partial y}{\\partial z}",
        "= 0 + 0 + 0 = 0 \\quad\\checkmark",
      ],
    },
    bullets: [
      "This identity holds for ANY twice-differentiable vector field",
      "Proof relies on equality of mixed partial derivatives",
      "Physical meaning: curl fields carry no net flux",
      "Used in Maxwell's equations and fluid mechanics",
    ],
    visual: "identities",
    narration: "Let us verify the identity that the divergence of the curl is always zero, using the field from our previous slide. We found curl A equals z i minus x j plus y k. Now we take the divergence: partial of z with respect to x is 0, partial of negative x with respect to y is 0, and partial of y with respect to z is 0. The sum is indeed zero, confirming the identity. This result holds for any twice-differentiable vector field, due to the symmetry of mixed partial derivatives. In physics, this means that curl-derived fields like the magnetic field in Maxwell's equations automatically have no magnetic monopoles.",
  },

  // ─────────────────────────────────────────────────────────────
  // YAHYA – Slides 13–16
  // ─────────────────────────────────────────────────────────────
  {
    id: 13,
    type: "content",
    presenter: "Yahya Omar Mahmoud Deyab",
    slideNum: 13,
    topic: "Scalar & Vector Fields — Overview",
    tag: "Fundamentals",
    tagColor: "blue",
    formulas: [
      { latex: "\\text{Scalar field: } \\phi = \\phi(x,y,z,t)", glow: "blue" },
      { latex: "\\text{Vector field: } \\mathbf{V} = V_1\\mathbf{i} + V_2\\mathbf{j} + V_3\\mathbf{k}", glow: "purple" },
    ],
    bullets: [
      "Scalar field: one value at every point (temperature, pressure, density)",
      "Vector field: three values at every point (velocity, force, electric field)",
      "Gradient converts scalar field → vector field",
      "Divergence / Curl operate on vector fields",
    ],
    visual: "fields",
    narration: "Before diving deeper into calculations, let us review scalar and vector fields. A scalar field assigns a single number to each point in space — examples include temperature distribution in a room, atmospheric pressure, or gravitational potential. A vector field assigns a full vector to each point — examples include velocity of a flowing fluid, the electric field around a charge, or the magnetic field in a motor. The gradient converts a scalar field into a vector field. The divergence and curl are operations that act on vector fields to extract physical information about sources and rotation.",
  },
  {
    id: 14,
    type: "content",
    presenter: "Yahya Omar Mahmoud Deyab",
    slideNum: 14,
    topic: "Gradient — Physical Interpretation",
    tag: "Physics",
    tagColor: "teal",
    formulas: [
      { latex: "\\mathbf{F} = -\\nabla V \\quad \\text{(Force from potential)}", glow: "teal" },
      { latex: "\\mathbf{E} = -\\nabla\\phi_{\\text{elec}} \\quad \\text{(Electric field)}", glow: "blue" },
    ],
    bullets: [
      "In mechanics: F = −∇V (force = negative gradient of potential energy)",
      "In electrostatics: E = −∇ϕ (electric field = negative gradient of potential)",
      "Negative sign: force opposes increase (downhill in energy)",
      "Gradient magnitude = force per unit charge / mass",
    ],
    visual: "potential",
    narration: "The gradient has profound physical meaning. In classical mechanics, the force on a particle equals negative gradient of the potential energy V. The negative sign is crucial: forces always push toward lower potential energy, like a ball rolling downhill. Similarly, in electrostatics, the electric field vector at any point equals the negative gradient of the electric potential. These relationships allow us to compute vector fields from much simpler scalar fields. This is one reason the gradient is so central to all of physics.",
  },
  {
    id: 15,
    type: "content",
    presenter: "Yahya Omar Mahmoud Deyab",
    slideNum: 15,
    topic: "Divergence — Physical Interpretation",
    tag: "Physics",
    tagColor: "teal",
    formulas: [
      { latex: "\\oint_S \\mathbf{V}\\cdot d\\mathbf{S} = \\iiint_V (\\nabla\\cdot\\mathbf{V})\\,dV", glow: "blue" },
      { latex: "\\text{(Gauss Divergence Theorem)}", glow: "teal" },
    ],
    bullets: [
      "Divergence = net outward flux per unit volume at a point",
      "Gauss's theorem: volume integral of divergence = surface flux integral",
      "∇·E = ρ/ε₀ (Gauss's law of electrostatics)",
      "∇·B = 0 (no magnetic monopoles)",
    ],
    visual: "gaussThm",
    narration: "The divergence theorem, also called Gauss's theorem, states that the integral of the divergence over a volume equals the net flux through the bounding surface. This is one of the most powerful theorems in vector calculus. It appears in Gauss's law: the divergence of the electric field equals the charge density divided by epsilon-naught. It also gives us the statement that the divergence of the magnetic field is zero everywhere — there are no magnetic monopoles in nature. Every textbook in electromagnetism, fluid dynamics, and thermodynamics uses this theorem constantly.",
  },
  {
    id: 16,
    type: "content",
    presenter: "Yahya Omar Mahmoud Deyab",
    slideNum: 16,
    topic: "Curl — Physical Interpretation",
    tag: "Physics",
    tagColor: "purple",
    formulas: [
      { latex: "\\oint_C \\mathbf{V}\\cdot d\\mathbf{r} = \\iint_S (\\nabla\\times\\mathbf{V})\\cdot d\\mathbf{S}", glow: "purple" },
      { latex: "\\text{(Stokes' Theorem)}", glow: "blue" },
    ],
    bullets: [
      "Curl = circulation per unit area at a point",
      "Stokes' theorem: circulation around curve = flux of curl through surface",
      "∇×E = −∂B/∂t (Faraday's law of induction)",
      "∇×B = μ₀J (Ampère's law)",
    ],
    visual: "stokesThm",
    narration: "Stokes' theorem relates the line integral of a vector field around a closed curve to the surface integral of its curl. This connects the local rotation described by the curl to the global circulation around a loop. In electromagnetism, Faraday's law states that the curl of the electric field equals the negative time derivative of the magnetic field — this is how electric generators work. Ampère's law states that the curl of the magnetic field is proportional to the current density. Together with the divergence theorem, Stokes' theorem encapsulates the entirety of Maxwell's equations in vector form.",
  },

  // ─────────────────────────────────────────────────────────────
  // AHMED SAIED – Slides 17–20
  // ─────────────────────────────────────────────────────────────
  {
    id: 17,
    type: "content",
    presenter: "Ahmed Saied ELsayed Kamal",
    slideNum: 17,
    topic: "Gradient Example — Normal to Surface",
    tag: "Example",
    tagColor: "teal",
    formulas: [
      { latex: "\\phi(x,y,z) = x^2 + y^2 + z^2 - 9 = 0 \\;\\text{(sphere of radius 3)}", glow: "blue" },
    ],
    example: {
      title: "Find unit normal at (1, 2, 2)",
      steps: [
        "\\nabla\\phi = 2x\\,\\mathbf{i} + 2y\\,\\mathbf{j} + 2z\\,\\mathbf{k}",
        "\\text{At }(1,2,2): \\;\\nabla\\phi = 2\\mathbf{i}+4\\mathbf{j}+4\\mathbf{k}",
        "|\\nabla\\phi| = \\sqrt{4+16+16} = \\sqrt{36} = 6",
        "\\hat{n} = \\frac{\\nabla\\phi}{|\\nabla\\phi|} = \\frac{1}{3}\\mathbf{i}+\\frac{2}{3}\\mathbf{j}+\\frac{2}{3}\\mathbf{k}",
      ],
    },
    bullets: [
      "Set the surface as ϕ(x,y,z) = 0",
      "Gradient gives the normal vector direction",
      "Divide by magnitude to get unit normal n̂",
      "Used in surface integrals, reflection, refraction",
    ],
    visual: "normalSurface",
    narration: "The gradient gives us a direct way to find the unit normal to a surface. Consider the sphere x squared plus y squared plus z squared equals 9, rewritten as phi equals x squared plus y squared plus z squared minus 9 equals zero. At the point (1, 2, 2), the gradient is 2i plus 4j plus 4k, with magnitude 6. The unit normal is therefore one-third i plus two-thirds j plus two-thirds k. This vector points radially outward from the center of the sphere at that point, exactly as expected. This technique works for any smooth surface defined by an equation phi equals zero.",
  },
  {
    id: 18,
    type: "content",
    presenter: "Ahmed Saied ELsayed Kamal",
    slideNum: 18,
    topic: "Divergence — Solenoidal Field",
    tag: "Example",
    tagColor: "blue",
    formulas: [
      { latex: "\\mathbf{F} = (x^2+y^2)\\mathbf{i} - 2xy\\,\\mathbf{j} + z^2\\mathbf{k}", glow: "blue" },
    ],
    example: {
      title: "Test if F is solenoidal",
      steps: [
        "\\frac{\\partial}{\\partial x}(x^2+y^2) = 2x",
        "\\frac{\\partial}{\\partial y}(-2xy) = -2x",
        "\\frac{\\partial}{\\partial z}(z^2) = 2z",
        "\\nabla\\cdot\\mathbf{F} = 2x - 2x + 2z = 2z",
        "\\text{Solenoidal only when }z=0\\text{ (not generally)}",
      ],
    },
    bullets: [
      "F is solenoidal only if ∇·F = 0 everywhere",
      "In this case ∇·F = 2z ≠ 0 (not solenoidal in 3D)",
      "Solenoidal fields represent incompressible flows",
      "Magnetic fields are always solenoidal (∇·B = 0)",
    ],
    visual: "divergence",
    narration: "Let us test whether the vector field F equals x squared plus y squared in i, minus 2xy in j, and z squared in k is solenoidal. We compute each partial: partial of x squared plus y squared with respect to x gives 2x. Partial of negative 2xy with respect to y gives negative 2x. Partial of z squared with respect to z gives 2z. The divergence is therefore 2x minus 2x plus 2z, which equals 2z. Since this is not zero everywhere, the field is not solenoidal in general. It is solenoidal only on the plane z equals zero. For a field to be solenoidal everywhere, it must represent an incompressible flow, like the magnetic field.",
  },
  {
    id: 19,
    type: "content",
    presenter: "Ahmed Saied ELsayed Kamal",
    slideNum: 19,
    topic: "Curl — Irrotational Field",
    tag: "Example",
    tagColor: "purple",
    formulas: [
      { latex: "\\mathbf{G} = y^2 z\\,\\mathbf{i} + 2xyz\\,\\mathbf{j} + xy^2\\mathbf{k}", glow: "purple" },
    ],
    example: {
      title: "Show ∇ × G = 0 (irrotational)",
      steps: [
        "\\mathbf{i}: \\frac{\\partial(xy^2)}{\\partial y} - \\frac{\\partial(2xyz)}{\\partial z} = 2xy - 2xy = 0",
        "\\mathbf{j}: \\frac{\\partial(y^2z)}{\\partial z} - \\frac{\\partial(xy^2)}{\\partial x} = y^2 - y^2 = 0",
        "\\mathbf{k}: \\frac{\\partial(2xyz)}{\\partial x} - \\frac{\\partial(y^2z)}{\\partial y} = 2yz - 2yz = 0",
        "\\nabla\\times\\mathbf{G} = \\mathbf{0} \\;\\checkmark",
      ],
    },
    bullets: [
      "All three components of curl vanish → G is irrotational",
      "Irrotational fields can be written as G = ∇ϕ for some ϕ",
      "Conservative force fields are irrotational",
      "Gravity and electrostatic forces are conservative",
    ],
    visual: "curlCalc",
    narration: "Now let us show that the field G equals y squared z i plus 2xyz j plus x y squared k is irrotational. We compute each component of the curl. The i-component is partial of xy squared with respect to y minus partial of 2xyz with respect to z, giving 2xy minus 2xy equals zero. The j-component is partial of y squared z with respect to z minus partial of xy squared with respect to x, giving y squared minus y squared equals zero. The k-component is partial of 2xyz with respect to x minus partial of y squared z with respect to y, giving 2yz minus 2yz equals zero. All three components are zero, confirming G is irrotational. This means G equals the gradient of some scalar potential phi.",
  },
  {
    id: 20,
    type: "content",
    presenter: "Ahmed Saied ELsayed Kamal",
    slideNum: 20,
    topic: "Directional Derivative — Extended Example",
    tag: "Example",
    tagColor: "teal",
    formulas: [
      { latex: "\\phi = x^2yz + 4xz^2 \\text{ at } P(1,-2,-1)", glow: "blue" },
      { latex: "\\text{Direction: }\\mathbf{a} = 2\\mathbf{i} - \\mathbf{j} - 2\\mathbf{k}", glow: "teal" },
    ],
    example: {
      title: "Find directional derivative",
      steps: [
        "\\nabla\\phi = (2xyz+4z^2)\\mathbf{i} + x^2z\\,\\mathbf{j} + (x^2y+8xz)\\mathbf{k}",
        "\\text{At }(1,-2,-1): \\;(4+4)\\mathbf{i}+(-1)\\mathbf{j}+(-2-8)\\mathbf{k} = 8\\mathbf{i}-\\mathbf{j}-10\\mathbf{k}",
        "\\hat{a} = \\tfrac{1}{3}(2\\mathbf{i}-\\mathbf{j}-2\\mathbf{k})",
        "\\frac{d\\phi}{ds} = (8)(\\tfrac{2}{3})+(-1)(\\tfrac{-1}{3})+(-10)(\\tfrac{-2}{3}) = \\tfrac{16+1+20}{3} = \\frac{37}{3}",
      ],
    },
    bullets: [
      "Compute ∇ϕ symbolically first",
      "Substitute point coordinates",
      "Normalize the direction vector",
      "Take dot product to get directional derivative",
    ],
    visual: "directional",
    narration: "Here is a detailed directional derivative example. Given phi equals x squared yz plus 4xz squared at the point (1, negative 2, negative 1), in the direction 2i minus j minus 2k. First we compute gradient phi symbolically: the partial with respect to x is 2xyz plus 4z squared, with respect to y is x squared z, and with respect to z is x squared y plus 8xz. At our point, these give 8i minus j minus 10k. The unit direction vector is one-third times 2i minus j minus 2k. The directional derivative is then 8 times 2/3, plus negative 1 times negative 1/3, plus negative 10 times negative 2/3, which equals 16/3 plus 1/3 plus 20/3 equals 37/3.",
  },

  // ─────────────────────────────────────────────────────────────
  // MAHMOUD WAEL – Slides 21–24
  // ─────────────────────────────────────────────────────────────
  {
    id: 21,
    type: "content",
    presenter: "Mahmoud Wael Mostafa Mahmoud",
    slideNum: 21,
    topic: "∇ Product Rules",
    tag: "Identities",
    tagColor: "gold",
    formulas: [
      { latex: "\\nabla(\\phi\\psi) = \\phi\\,\\nabla\\psi + \\psi\\,\\nabla\\phi", glow: "gold" },
      { latex: "\\nabla\\cdot(\\phi\\mathbf{A}) = \\phi(\\nabla\\cdot\\mathbf{A}) + \\mathbf{A}\\cdot(\\nabla\\phi)", glow: "blue" },
      { latex: "\\nabla\\times(\\phi\\mathbf{A}) = \\phi(\\nabla\\times\\mathbf{A}) - \\mathbf{A}\\times(\\nabla\\phi)", glow: "purple" },
    ],
    bullets: [
      "Product rules mirror ordinary calculus (product rule)",
      "Both scalar and vector products have analogous rules",
      "Used extensively in simplifying PDE solutions",
      "Key to deriving Green's identities",
    ],
    visual: "identities",
    narration: "Just like in ordinary single-variable calculus, there are product rules for the nabla operator. The gradient of a product of two scalars phi and psi equals phi times gradient of psi plus psi times gradient of phi. The divergence of phi times vector A equals phi times divergence of A plus A dot gradient of phi. The curl of phi times A equals phi times curl of A minus A cross gradient of phi. These identities are used constantly to simplify complex vector calculus expressions, and they are the foundation for deriving Green's integral theorems.",
  },
  {
    id: 22,
    type: "content",
    presenter: "Mahmoud Wael Mostafa Mahmoud",
    slideNum: 22,
    topic: "Second-Order Operators",
    tag: "Identities",
    tagColor: "gold",
    formulas: [
      { latex: "\\nabla^2\\phi = \\nabla\\cdot(\\nabla\\phi) \\quad\\text{(Laplacian)}", glow: "blue" },
      { latex: "\\nabla\\times(\\nabla\\times\\mathbf{A}) = \\nabla(\\nabla\\cdot\\mathbf{A}) - \\nabla^2\\mathbf{A}", glow: "gold" },
      { latex: "\\nabla\\cdot(\\nabla\\times\\mathbf{A}) = 0,\\quad \\nabla\\times(\\nabla\\phi)=\\mathbf{0}", glow: "purple" },
    ],
    bullets: [
      "Laplacian = divergence of gradient",
      "curl(curl A) = grad(div A) − ∇²A (vector identity)",
      "Two zero identities: div·curl = 0, curl·grad = 0",
      "Vector Laplacian: ∇²A = (∇²A₁)i + (∇²A₂)j + (∇²A₃)k",
    ],
    visual: "identities",
    narration: "The second-order differential operators are even more powerful. The Laplacian of a scalar is the divergence of its gradient. For vectors, there is a beautiful identity: curl of curl of A equals gradient of divergence of A minus the vector Laplacian of A. This identity is crucially used in electromagnetic wave theory. We also recall the two zero identities: divergence of curl is zero, and curl of gradient is zero. Together these four second-order results form the algebraic skeleton of mathematical physics.",
  },
  {
    id: 23,
    type: "content",
    presenter: "Mahmoud Wael Mostafa Mahmoud",
    slideNum: 23,
    topic: "Gradient in Curvilinear Coordinates",
    tag: "Extension",
    tagColor: "blue",
    formulas: [
      { latex: "\\nabla\\phi = \\hat{r}\\frac{\\partial\\phi}{\\partial r} + \\hat{\\theta}\\frac{1}{r}\\frac{\\partial\\phi}{\\partial\\theta} + \\hat{\\phi}\\frac{1}{r\\sin\\theta}\\frac{\\partial\\phi}{\\partial\\varphi} \\;\\text{(spherical)}", glow: "blue" },
      { latex: "\\nabla\\phi = \\hat{\\rho}\\frac{\\partial\\phi}{\\partial\\rho} + \\hat{\\varphi}\\frac{1}{\\rho}\\frac{\\partial\\phi}{\\partial\\varphi} + \\hat{z}\\frac{\\partial\\phi}{\\partial z} \\;\\text{(cylindrical)}", glow: "purple" },
    ],
    bullets: [
      "Cartesian coordinates are not always the most convenient",
      "Spherical: natural for problems with spherical symmetry",
      "Cylindrical: natural for cylindrical or axial symmetry",
      "Scale factors h₁, h₂, h₃ modify the derivative terms",
    ],
    visual: "coordinates",
    narration: "In many physical problems, the geometry naturally suggests spherical or cylindrical coordinates rather than Cartesian. In spherical coordinates r, theta, phi, the gradient has scale factors of 1, 1 over r, and 1 over r sine theta. In cylindrical coordinates rho, phi, z, the scale factors are 1, 1 over rho, and 1. These scale factors arise because the coordinate axes are not uniformly spaced — moving in the theta direction by one radian corresponds to different arc lengths depending on how far you are from the origin. Choosing the right coordinate system can dramatically simplify a calculation.",
  },
  {
    id: 24,
    type: "content",
    presenter: "Mahmoud Wael Mostafa Mahmoud",
    slideNum: 24,
    topic: "Laplacian in Cylindrical & Spherical Coordinates",
    tag: "Extension",
    tagColor: "teal",
    formulas: [
      { latex: "\\nabla^2\\phi = \\frac{1}{\\rho}\\frac{\\partial}{\\partial\\rho}\\!\\left(\\rho\\frac{\\partial\\phi}{\\partial\\rho}\\right) + \\frac{1}{\\rho^2}\\frac{\\partial^2\\phi}{\\partial\\varphi^2} + \\frac{\\partial^2\\phi}{\\partial z^2} \\;\\text{(cyl.)}", glow: "teal" },
      { latex: "\\nabla^2\\phi = \\frac{1}{r^2}\\frac{\\partial}{\\partial r}\\!\\left(r^2\\frac{\\partial\\phi}{\\partial r}\\right) + \\frac{1}{r^2\\sin\\theta}\\frac{\\partial}{\\partial\\theta}\\!\\left(\\sin\\theta\\frac{\\partial\\phi}{\\partial\\theta}\\right) + \\frac{1}{r^2\\sin^2\\theta}\\frac{\\partial^2\\phi}{\\partial\\varphi^2} \\;\\text{(sph.)}", glow: "blue" },
    ],
    bullets: [
      "Same Laplacian operator, different coordinate expressions",
      "Spherical form: separates into radial and angular parts",
      "Angular part → Legendre polynomials, spherical harmonics",
      "Radial part → Bessel functions, power-law solutions",
    ],
    visual: "laplacian",
    narration: "The Laplacian expressed in cylindrical and spherical coordinates takes more complex but highly structured forms. In cylindrical coordinates, we get the rho derivative term, the phi term, and the z term. In spherical coordinates, the radial and angular parts separate cleanly. This separation is the basis of separation of variables — a powerful technique for solving partial differential equations. The angular part of the spherical Laplacian leads to the spherical harmonics, which describe the shapes of atomic orbitals and the angular parts of solutions to Schrödinger's equation.",
  },

  // ─────────────────────────────────────────────────────────────
  // AMR HAMDY – Slides 25–28
  // ─────────────────────────────────────────────────────────────
  {
    id: 25,
    type: "content",
    presenter: "Amr Hamdy Fathy Abdel Salam",
    slideNum: 25,
    topic: "Divergence Theorem — Statement",
    tag: "Theorem",
    tagColor: "blue",
    formulas: [
      { latex: "\\oiint_S \\mathbf{F}\\cdot\\hat{n}\\,dS = \\iiint_V (\\nabla\\cdot\\mathbf{F})\\,dV", glow: "blue" },
    ],
    bullets: [
      "Relates triple volume integral to double surface integral",
      "n̂ = outward unit normal to surface S bounding volume V",
      "Converts difficult surface integrals into volume integrals",
      "Fundamental tool: fluid dynamics, electrostatics, heat flow",
    ],
    visual: "gaussThm",
    narration: "The Divergence Theorem, also known as Gauss's theorem, is one of the most powerful results in vector calculus. It states that the surface integral of a vector field F over a closed surface S equals the triple integral of its divergence over the enclosed volume V. In practical terms, this allows us to convert a surface integral, which may be hard to compute, into a volume integral, which is often easier. It also provides the physical interpretation of divergence as the net outward flux per unit volume.",
  },
  {
    id: 26,
    type: "content",
    presenter: "Amr Hamdy Fathy Abdel Salam",
    slideNum: 26,
    topic: "Divergence Theorem — Example",
    tag: "Example",
    tagColor: "teal",
    formulas: [
      { latex: "\\mathbf{F} = x^2\\mathbf{i} + y^2\\mathbf{j} + z^2\\mathbf{k}, \\quad V = \\text{unit cube}", glow: "blue" },
    ],
    example: {
      title: "Compute flux via Divergence Theorem",
      steps: [
        "\\nabla\\cdot\\mathbf{F} = 2x + 2y + 2z",
        "\\iiint_V (2x+2y+2z)\\,dV = 2\\int_0^1\\!\\int_0^1\\!\\int_0^1(x+y+z)\\,dx\\,dy\\,dz",
        "= 2\\int_0^1\\!\\int_0^1 (\\tfrac{1}{2}+y+z)\\,dy\\,dz = 2\\int_0^1(1+z)\\,dz",
        "= 2\\left[z + \\tfrac{z^2}{2}\\right]_0^1 = 2\\cdot\\tfrac{3}{2} = 3",
      ],
    },
    bullets: [
      "Step 1: Compute divergence of F",
      "Step 2: Set up triple integral over volume",
      "Step 3: Evaluate iterated integrals",
      "Step 4: Result = net flux through all six faces",
    ],
    visual: "gaussThm",
    narration: "Let us apply the Divergence Theorem to F equals x squared i plus y squared j plus z squared k over the unit cube from 0 to 1 in each direction. The divergence is 2x plus 2y plus 2z. We integrate this over the unit cube. Integrating first with respect to x gives one-half plus y plus z over each dy-dz element. Then integrating with respect to y gives 1 plus z. Integrating with respect to z from 0 to 1 gives z plus z squared over 2, evaluated to 3 halves. Multiplying by 2 gives the total flux of 3. This equals the sum of the fluxes through all six faces of the cube.",
  },
  {
    id: 27,
    type: "content",
    presenter: "Amr Hamdy Fathy Abdel Salam",
    slideNum: 27,
    topic: "Stokes' Theorem — Statement",
    tag: "Theorem",
    tagColor: "purple",
    formulas: [
      { latex: "\\oint_C \\mathbf{F}\\cdot d\\mathbf{r} = \\iint_S (\\nabla\\times\\mathbf{F})\\cdot\\hat{n}\\,dS", glow: "purple" },
    ],
    bullets: [
      "Relates line integral around closed curve C to surface integral of curl",
      "S = any surface bounded by the curve C",
      "Orientation: right-hand rule between curve and surface normal",
      "Generalizes Green's theorem to 3D",
    ],
    visual: "stokesThm",
    narration: "Stokes' theorem states that the line integral of F around a closed curve C equals the surface integral of the curl of F over any surface S bounded by C. The orientation is determined by the right-hand rule: if your thumb points in the direction of n-hat, your fingers curl in the positive direction of traversal of C. This theorem generalizes Green's theorem in the plane to three-dimensional surfaces. It is fundamental to the derivation of Faraday's law of electromagnetic induction.",
  },
  {
    id: 28,
    type: "content",
    presenter: "Amr Hamdy Fathy Abdel Salam",
    slideNum: 28,
    topic: "Stokes' Theorem — Example",
    tag: "Example",
    tagColor: "purple",
    formulas: [
      { latex: "\\mathbf{F} = (2x-y)\\mathbf{i} - yz^2\\mathbf{j} - y^2z\\mathbf{k}", glow: "purple" },
      { latex: "S\\text{: upper hemisphere }x^2+y^2+z^2=1,\\;z\\geq0", glow: "blue" },
    ],
    example: {
      title: "Apply Stokes' Theorem",
      steps: [
        "\\nabla\\times\\mathbf{F}: \\;\\mathbf{i}(-2yz+2yz)-\\mathbf{j}(0-0)+\\mathbf{k}(0+1) = \\mathbf{k}",
        "\\iint_S \\mathbf{k}\\cdot\\hat{n}\\,dS = \\iint_S \\cos\\gamma\\,dS",
        "\\text{On hemisphere: }\\hat{n}=\\hat{r},\\;\\mathbf{k}\\cdot\\hat{n}=\\cos\\theta",
        "\\text{Result: }\\oint_C \\mathbf{F}\\cdot d\\mathbf{r} = \\pi",
      ],
    },
    bullets: [
      "Compute curl F first",
      "Project curl onto surface normal n̂",
      "Integrate over surface — hemisphere simplifies nicely",
      "Stokes converts the line integral to surface integral",
    ],
    visual: "stokesThm",
    narration: "Let us apply Stokes' theorem to the field F equals 2x minus y in i, minus yz squared in j, minus y squared z in k, over the upper hemisphere of the unit sphere. We first compute the curl of F. After careful computation, the curl simplifies to just k. The Stokes integral then becomes the surface integral of k dotted with the outward normal of the hemisphere. On the hemisphere, k dotted with the normal equals cosine of the polar angle theta. Integrating this over the hemisphere gives pi, which is exactly the line integral of F around the equator.",
  },

  // ─────────────────────────────────────────────────────────────
  // ABDELRAHMAN – Slides 29–32
  // ─────────────────────────────────────────────────────────────
  {
    id: 29,
    type: "content",
    presenter: "Abdelrahman Mahmoud Elsayed Mahmoud",
    slideNum: 29,
    topic: "Conservative Fields & Scalar Potential",
    tag: "Theory",
    tagColor: "gold",
    formulas: [
      { latex: "\\mathbf{F} = \\nabla\\phi \\;\\Leftrightarrow\\; \\nabla\\times\\mathbf{F} = 0 \\;\\text{(in simply connected region)}", glow: "gold" },
      { latex: "\\int_A^B \\mathbf{F}\\cdot d\\mathbf{r} = \\phi(B) - \\phi(A) \\quad\\text{(path independent)}", glow: "blue" },
    ],
    bullets: [
      "F is conservative ↔ F = ∇ϕ for some scalar ϕ",
      "Equivalently: ∇ × F = 0 (irrotational)",
      "Work done is path-independent",
      "Gravity, electrostatics, elasticity: all conservative",
    ],
    visual: "potential",
    narration: "A vector field F is called conservative if it can be written as the gradient of a scalar potential phi. The fundamental equivalence is: F is conservative if and only if its curl is zero everywhere in a simply connected region. The profound consequence is that the line integral of F from point A to point B equals phi at B minus phi at A — it does not depend on the path taken. This is why gravity and electrostatic forces are conservative: the work done lifting a book does not depend on which route you take, only on the initial and final heights.",
  },
  {
    id: 30,
    type: "content",
    presenter: "Abdelrahman Mahmoud Elsayed Mahmoud",
    slideNum: 30,
    topic: "Finding the Scalar Potential",
    tag: "Method",
    tagColor: "teal",
    formulas: [
      { latex: "\\mathbf{F} = (2xy+z^2)\\mathbf{i}+x^2\\mathbf{j}+2xz\\mathbf{k}", glow: "blue" },
    ],
    example: {
      title: "Find ϕ such that F = ∇ϕ",
      steps: [
        "\\frac{\\partial\\phi}{\\partial x}=2xy+z^2 \\;\\Rightarrow\\; \\phi = x^2y+xz^2+g(y,z)",
        "\\frac{\\partial\\phi}{\\partial y}=x^2+\\frac{\\partial g}{\\partial y}=x^2 \\;\\Rightarrow\\; \\frac{\\partial g}{\\partial y}=0 \\;\\Rightarrow\\; g=h(z)",
        "\\frac{\\partial\\phi}{\\partial z}=2xz+h'(z)=2xz \\;\\Rightarrow\\; h'(z)=0 \\;\\Rightarrow\\; h=C",
        "\\phi = x^2y + xz^2 + C",
      ],
    },
    bullets: [
      "Integrate ∂ϕ/∂x to get ϕ up to a function of y, z",
      "Use ∂ϕ/∂y to determine the y-dependence",
      "Use ∂ϕ/∂z to determine the z-dependence",
      "Result: scalar potential (up to a constant)",
    ],
    visual: "potential",
    narration: "Here is how to find the scalar potential systematically. Given F equals 2xy plus z squared in i, x squared in j, and 2xz in k, we integrate the x-component: phi equals x squared y plus xz squared plus g of y and z. Differentiating with respect to y and setting it equal to the j-component gives partial g over partial y equals zero, so g is a function of z only. Differentiating with respect to z gives 2xz plus h prime of z equals 2xz, so h prime equals zero and h is a constant. Therefore the scalar potential is phi equals x squared y plus xz squared plus C.",
  },
  {
    id: 31,
    type: "content",
    presenter: "Abdelrahman Mahmoud Elsayed Mahmoud",
    slideNum: 31,
    topic: "Green's Theorem in the Plane",
    tag: "Theorem",
    tagColor: "blue",
    formulas: [
      { latex: "\\oint_C (P\\,dx + Q\\,dy) = \\iint_D \\left(\\frac{\\partial Q}{\\partial x} - \\frac{\\partial P}{\\partial y}\\right)dA", glow: "blue" },
    ],
    bullets: [
      "2D special case of Stokes' theorem",
      "C = positively oriented (counterclockwise) simple closed curve",
      "D = region enclosed by C",
      "Used to compute areas: A = ½ ∮(x dy − y dx)",
    ],
    visual: "stokesThm",
    narration: "Green's theorem is the two-dimensional version of Stokes' theorem. It states that the line integral of P dx plus Q dy around a positively oriented closed curve C equals the double integral over the enclosed region D of partial Q over partial x minus partial P over partial y. This is extremely useful for computing areas and evaluating line integrals by converting them to easier double integrals. The formula A equals one-half times the line integral of x dy minus y dx is a direct application of Green's theorem to compute areas.",
  },
  {
    id: 32,
    type: "content",
    presenter: "Abdelrahman Mahmoud Elsayed Mahmoud",
    slideNum: 32,
    topic: "Vector Fields in Fluid Mechanics",
    tag: "Applications",
    tagColor: "teal",
    formulas: [
      { latex: "\\frac{D\\mathbf{u}}{Dt} = -\\frac{1}{\\rho}\\nabla p + \\nu\\,\\nabla^2\\mathbf{u} + \\mathbf{g} \\quad\\text{(Navier–Stokes)}", glow: "teal" },
      { latex: "\\nabla\\cdot\\mathbf{u} = 0 \\quad\\text{(incompressible continuity)}", glow: "blue" },
    ],
    bullets: [
      "Navier–Stokes: contains gradient (pressure), Laplacian (viscosity), body force",
      "Incompressible: velocity field is solenoidal",
      "Vorticity: ω = ∇ × u (curl of velocity)",
      "All three operators (∇, ∇·, ∇×) appear in fluid mechanics",
    ],
    visual: "fields",
    narration: "Vector calculus is the language of fluid mechanics. The Navier-Stokes equations, which govern all viscous fluid flow, contain a gradient of pressure, a Laplacian of velocity for viscous diffusion, and a body force term. The incompressibility condition for liquids is simply that the divergence of the velocity field is zero — a solenoidal field. The vorticity of the flow, which describes spinning and turbulence, is the curl of the velocity. You can see that gradient, divergence, and curl all appear together in the fundamental equations of fluid dynamics.",
  },

  // ─────────────────────────────────────────────────────────────
  // BELAL – Slides 33–36
  // ─────────────────────────────────────────────────────────────
  {
    id: 33,
    type: "content",
    presenter: "Belal Elsayed Saad Elsayed",
    slideNum: 33,
    topic: "Gradient — Level Curves & Tangent Planes",
    tag: "Geometry",
    tagColor: "purple",
    formulas: [
      { latex: "\\text{Tangent plane to }\\phi=c\\text{ at }P_0:\\quad \\nabla\\phi|_{P_0}\\cdot(\\mathbf{r}-\\mathbf{r}_0)=0", glow: "purple" },
      { latex: "\\text{Normal line: }\\mathbf{r}(t) = \\mathbf{r}_0 + t\\,\\nabla\\phi|_{P_0}", glow: "blue" },
    ],
    bullets: [
      "Tangent plane at P₀: all directions perpendicular to ∇ϕ",
      "Normal line passes through P₀ along ∇ϕ direction",
      "Used in multivariable optimization (Lagrange multipliers)",
      "Essential for surface geometry and differential geometry",
    ],
    visual: "normalSurface",
    narration: "The gradient vector defines both the tangent plane and the normal line to a surface. At a point P0 on the surface phi equals c, the tangent plane consists of all displacement vectors dr that are perpendicular to gradient phi at P0. The equation of the tangent plane is therefore gradient phi at P0 dotted with r minus r0 equals zero. The normal line to the surface at P0 passes in the direction of gradient phi, so its parametric equation is r of t equals r0 plus t times gradient phi at P0. These geometric tools are used in Lagrange multiplier optimization and in computing curvatures of surfaces.",
  },
  {
    id: 34,
    type: "content",
    presenter: "Belal Elsayed Saad Elsayed",
    slideNum: 34,
    topic: "Divergence — Conservation Laws",
    tag: "Physics",
    tagColor: "blue",
    formulas: [
      { latex: "\\frac{\\partial\\rho}{\\partial t} + \\nabla\\cdot(\\rho\\mathbf{u}) = 0 \\quad\\text{(continuity equation)}", glow: "blue" },
      { latex: "\\frac{\\partial\\mathbf{B}}{\\partial t} + \\nabla\\cdot\\mathbf{E}\\times\\mathbf{B} = 0 \\quad\\text{(Poynting — energy conservation)}", glow: "teal" },
    ],
    bullets: [
      "Continuity: mass cannot be created or destroyed",
      "Divergence form expresses local conservation at every point",
      "Integrating + Divergence theorem → global conservation",
      "All conservation laws (energy, momentum, charge) use ∇·",
    ],
    visual: "gaussThm",
    narration: "The divergence is the natural tool for expressing conservation laws. The continuity equation, which expresses conservation of mass, states that the partial derivative of density with respect to time plus the divergence of the momentum density rho-u equals zero. Every point either gains or loses mass only through flux entering or leaving it. By integrating this equation over a volume and applying the divergence theorem, we get the global conservation law: the rate of change of total mass in the volume equals the net flux through the surface. This principle applies to all conserved quantities in nature.",
  },
  {
    id: 35,
    type: "content",
    presenter: "Belal Elsayed Saad Elsayed",
    slideNum: 35,
    topic: "Curl — Vorticity & Rotation",
    tag: "Physics",
    tagColor: "purple",
    formulas: [
      { latex: "\\boldsymbol{\\omega} = \\nabla\\times\\mathbf{u} \\quad\\text{(vorticity vector)}", glow: "purple" },
      { latex: "\\mathbf{u} = \\boldsymbol{\\Omega}\\times\\mathbf{r} \\;\\Rightarrow\\; \\nabla\\times\\mathbf{u} = 2\\boldsymbol{\\Omega}", glow: "blue" },
    ],
    bullets: [
      "Vorticity ω = curl(u) describes rotation in fluid flow",
      "Rigid body rotation: curl of velocity = 2 × angular velocity",
      "Irrotational flow: ω = 0 (potential flow theory)",
      "Kelvin's theorem: vorticity is conserved in inviscid flow",
    ],
    visual: "curlCalc",
    narration: "The curl of a velocity field gives the vorticity, the local spinning motion in a fluid. For a rigid body rotating with angular velocity Omega, the velocity field is Omega cross r, and its curl equals exactly 2 Omega. So the curl gives twice the angular velocity of rotation. In fluid mechanics, regions of high vorticity correspond to turbulent eddies and swirling structures. Potential flow theory assumes zero vorticity everywhere, which greatly simplifies the mathematics. The conservation of vorticity in inviscid flows is Kelvin's circulation theorem, one of the jewels of fluid dynamics.",
  },
  {
    id: 36,
    type: "content",
    presenter: "Belal Elsayed Saad Elsayed",
    slideNum: 36,
    topic: "Maxwell's Equations in Vector Form",
    tag: "Physics",
    tagColor: "gold",
    formulas: [
      { latex: "\\nabla\\cdot\\mathbf{E}=\\frac{\\rho}{\\varepsilon_0},\\quad \\nabla\\cdot\\mathbf{B}=0", glow: "blue" },
      { latex: "\\nabla\\times\\mathbf{E}=-\\frac{\\partial\\mathbf{B}}{\\partial t},\\quad \\nabla\\times\\mathbf{B}=\\mu_0\\mathbf{J}+\\mu_0\\varepsilon_0\\frac{\\partial\\mathbf{E}}{\\partial t}", glow: "gold" },
    ],
    bullets: [
      "All of electromagnetism in 4 compact vector equations",
      "∇· equations: electric charges exist; no magnetic charges",
      "∇× equations: Faraday's law; Ampère + Maxwell's correction",
      "Predict light as electromagnetic waves: c = 1/√(μ₀ε₀)",
    ],
    visual: "identities",
    narration: "Maxwell's four equations, written in vector form, encapsulate all of classical electromagnetism. The first states the divergence of the electric field equals charge density over epsilon-naught — Gauss's law. The second states the divergence of the magnetic field is zero — no magnetic monopoles. The third states the curl of the electric field equals negative partial of B with respect to time — Faraday's induction law. The fourth states the curl of B equals mu-naught times J plus the displacement current — Ampère's generalized law. From these four equations, Maxwell derived that electromagnetic waves travel at the speed of light, predicting the unification of electricity, magnetism, and light.",
  },

  // ─────────────────────────────────────────────────────────────
  // AHMED KHALED – Slides 37–40
  // ─────────────────────────────────────────────────────────────
  {
    id: 37,
    type: "content",
    presenter: "Ahmed Khaled Ramadan Mohamed",
    slideNum: 37,
    topic: "Summary: The Three Operators",
    tag: "Summary",
    tagColor: "gold",
    formulas: [
      { latex: "\\text{Gradient: }\\nabla\\phi \\;\\text{ (scalar → vector, direction of increase)}", glow: "blue" },
      { latex: "\\text{Divergence: }\\nabla\\cdot\\mathbf{V} \\;\\text{ (vector → scalar, source/sink)}", glow: "teal" },
      { latex: "\\text{Curl: }\\nabla\\times\\mathbf{V} \\;\\text{ (vector → vector, rotation)}", glow: "purple" },
    ],
    bullets: [
      "Gradient: tells you which way to go for maximum increase",
      "Divergence: tells you how much a field spreads out",
      "Curl: tells you how much a field rotates",
      "All three built from the same nabla operator ∇",
    ],
    visual: "nabla",
    narration: "Let us consolidate our understanding. The three fundamental operators are all constructed from the same nabla operator. The gradient of a scalar gives a vector pointing in the direction of maximum increase — it converts a scalar field to a vector field. The divergence of a vector gives a scalar measuring how much the field spreads from a point — it converts a vector field to a scalar field. The curl of a vector gives a vector measuring rotation — it converts a vector field to another vector field. Together they form the complete toolkit for describing how scalar and vector fields vary in space.",
  },
  {
    id: 38,
    type: "content",
    presenter: "Ahmed Khaled Ramadan Mohamed",
    slideNum: 38,
    topic: "Summary: Key Identities Table",
    tag: "Summary",
    tagColor: "gold",
    formulas: [
      { latex: "\\nabla\\times(\\nabla\\phi)=\\mathbf{0}, \\quad \\nabla\\cdot(\\nabla\\times\\mathbf{A})=0", glow: "gold" },
      { latex: "\\nabla^2\\phi = \\nabla\\cdot(\\nabla\\phi), \\quad \\nabla(\\phi\\psi)=\\phi\\nabla\\psi+\\psi\\nabla\\phi", glow: "blue" },
      { latex: "\\nabla\\cdot(\\phi\\mathbf{A})=\\phi\\nabla\\cdot\\mathbf{A}+\\mathbf{A}\\cdot\\nabla\\phi", glow: "purple" },
    ],
    bullets: [
      "Two zero identities: curl-grad = 0, div-curl = 0",
      "Laplacian = div of grad",
      "Product rules mirror single-variable calculus",
      "These 5 identities appear in almost every physics derivation",
    ],
    visual: "identities",
    narration: "Here is a comprehensive summary of the key identities we have studied. First, the two zero identities: curl of gradient is zero, and divergence of curl is zero. These follow from the symmetry of mixed partial derivatives. Second, the Laplacian equals the divergence of the gradient. Third, the product rule for gradient of a product of scalars. Fourth, the product rule for divergence of a scalar times a vector. Memorizing these five identities will dramatically speed up vector calculus computations in any advanced physics or engineering course.",
  },
  {
    id: 39,
    type: "content",
    presenter: "Ahmed Khaled Ramadan Mohamed",
    slideNum: 39,
    topic: "Summary: Integral Theorems",
    tag: "Summary",
    tagColor: "teal",
    formulas: [
      { latex: "\\text{Divergence Thm: }\\oiint_S \\mathbf{F}\\cdot d\\mathbf{S} = \\iiint_V \\nabla\\cdot\\mathbf{F}\\,dV", glow: "teal" },
      { latex: "\\text{Stokes' Thm: }\\oint_C \\mathbf{F}\\cdot d\\mathbf{r} = \\iint_S \\nabla\\times\\mathbf{F}\\cdot d\\mathbf{S}", glow: "purple" },
      { latex: "\\text{Green's Thm: }\\oint_C (P\\,dx+Q\\,dy) = \\iint_D\\left(\\frac{\\partial Q}{\\partial x}-\\frac{\\partial P}{\\partial y}\\right)dA", glow: "blue" },
    ],
    bullets: [
      "Divergence theorem: volume ↔ surface (via div)",
      "Stokes' theorem: surface ↔ curve (via curl)",
      "Green's theorem: planar version of Stokes'",
      "All relate local (differential) to global (integral) behavior",
    ],
    visual: "gaussThm",
    narration: "The three integral theorems provide bridges between different levels of integration. The Divergence theorem converts triple integrals over volumes to double integrals over their bounding surfaces using the divergence. Stokes' theorem converts surface integrals to line integrals around boundaries using the curl. Green's theorem is the two-dimensional special case of Stokes'. Together they form a unified framework: every integral theorem relates an integral over a region to an integral over its boundary, connecting local differential properties to global geometric properties.",
  },
  {
    id: 40,
    type: "content",
    presenter: "Ahmed Khaled Ramadan Mohamed",
    slideNum: 40,
    topic: "Conclusion & Applications Overview",
    tag: "Conclusion",
    tagColor: "gold",
    formulas: [
      { latex: "\\nabla,\\;\\nabla\\cdot,\\;\\nabla\\times,\\;\\nabla^2 \\;\\longrightarrow\\; \\text{The full language of field theory}", glow: "gold" },
    ],
    bullets: [
      "Classical Mechanics: F = −∇V, equations of motion",
      "Electromagnetism: Maxwell's equations — 4 vector equations",
      "Fluid Dynamics: Navier–Stokes, vorticity, continuity",
      "Quantum Mechanics: Schrödinger equation contains ∇²",
      "General Relativity: curved spacetime generalizes ∇",
    ],
    visual: "gradient3d",
    narration: "We conclude Chapter 1 with a panoramic view of applications. The four operators — gradient, divergence, curl, and Laplacian — are the complete toolkit for describing physical fields. In classical mechanics, they describe forces and potentials. In electromagnetism, Maxwell's four vector equations use all of them. In fluid dynamics, the Navier-Stokes equations contain gradient of pressure, Laplacian of velocity, and the divergence-free condition. In quantum mechanics, the Schrödinger equation contains the Laplacian. Even in Einstein's general relativity, these operators generalize to curved spacetime. Mastering gradient, divergence, and curl is mastering the mathematical foundation of all modern physics.",
  },
];
